Replace concrete KafkaConsumers with Suppliers
MarkOSIndustries/distroboy pull request #3
Opened 2022-11-06 01:43 UTC by meenie216

KafkaConsumers are not thread safe - using the same KafkaConsumer in both the `KafkaTopicPartitionSource` and `ReadKafkaTopicPartitionRange` would result in exceptions being thrown by the consumer as it detected being used on different threads.

This change replaces the KafkaConsumers with Suppliers to step around this issue.

2022-11-07 12:03 UTC, MarkOSIndustries requested changes
Thanks for doing this Meenie, I've made some suggestions inline....

2022-11-07 12:03 UTC, MarkOSIndustries commented on example/src/main/java/com/markosindustries/distroboy/example/ExampleKafkaConsumer.java
> +                        () -> new KafkaConsumer<byte[], byte[]>(kafkaConfig),
I like this because it improves the communication to calling code that we need a new KafkaConsumer that we "own".
I was thinking about the possibility for people to provide memoized suppliers (like Guava has) and thwart our attempts at avoiding sharing KafkaConsumers between threads. I think maybe a better idea is to simply make the Consumer configuration the constructor argument, and we'll new up the KafkaConsumer at the point where we need it.

2022-11-07 12:03 UTC, MarkOSIndustries commented on kafka/src/main/java/com/markosindustries/distroboy/kafka/ReadKafkaTopicPartitionRange.java
> +    this.kafkaConsumer = kafkaConsumerSupplier.get();
I think we should defer `new`ing up the `KafkaConsumer` to the `KafkaTopicPartitionsIterator` constructor, rather than `new` it up here.
That way `KafkaTopicPartitionsIterator` also becomes safer to use in isolation.
Since we would then own the `KafkaConsumer` and its lifecycle, we can then also make `KafkaTopicPartitionsIterator` implement `AutoCloseable` and close the `KafkaConsumer`. It would then get closed cleanly when the `ReadTopicPartitionRange` iteration has completed, rather than being the responsibility of the calling code to decide when to close it.

2022-11-07 22:07 UTC, meenie216 commented on kafka/src/main/java/com/markosindustries/distroboy/kafka/ReadKafkaTopicPartitionRange.java
> +    this.kafkaConsumer = kafkaConsumerSupplier.get();
Agreed - I pondered this at the time!

Made `KafkaTopicPartitionsIterator` implement the `IteratorWithResources`

2022-11-07 22:07 UTC, meenie216 commented on example/src/main/java/com/markosindustries/distroboy/example/ExampleKafkaConsumer.java
> +                        () -> new KafkaConsumer<byte[], byte[]>(kafkaConfig),
Nice - makes sense to get in the way of memoized suppliers!

2022-11-08 00:02 UTC, MarkOSIndustries approved these changes
LGTM, thanks!

2022-11-08 00:02 UTC, merged